CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    email varchar(254) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(20) NOT NULL DEFAULT 'user',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('user', 'admin'))
);

CREATE TABLE books (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    author varchar(255) NOT NULL,
    genre varchar(100) NOT NULL,
    publication_year integer,
    description text NOT NULL DEFAULT '',
    isbn varchar(32),
    cover_url text,
    text_file_path text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_books_publication_year CHECK (publication_year > 0),
    CONSTRAINT uq_books_isbn UNIQUE (isbn)
);

CREATE INDEX ix_books_title ON books (title);
CREATE INDEX ix_books_author ON books (author);
CREATE INDEX ix_books_genre ON books (genre);

CREATE TABLE reviews (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id integer NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    rating smallint NOT NULL,
    text text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_reviews_user_book UNIQUE (user_id, book_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX ix_reviews_user_id ON reviews (user_id);
CREATE INDEX ix_reviews_book_id ON reviews (book_id);

CREATE TABLE favorites (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id integer NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, book_id)
);

CREATE INDEX ix_favorites_book_id ON favorites (book_id);

CREATE TABLE reading_list (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id integer NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, book_id)
);

CREATE INDEX ix_reading_list_book_id ON reading_list (book_id);

CREATE TABLE reading_history (
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id integer NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    read_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, book_id)
);

CREATE INDEX ix_reading_history_book_id ON reading_history (book_id);
